-- BuilderAI.tools schema summary.
--
-- This file is a clean reference snapshot of the application's database
-- schema, prepared for the public portfolio repository. It is not the
-- operational source of truth.
--
-- The full incremental migration history (one-off fixes, search_path
-- hotfixes, category merges, ban-system rollouts, RLS-policy iteration,
-- and similar) lives in the private development repository. None of that
-- history is needed to read or understand the design; what follows is
-- the shape of the production tables as they stand.
--
-- Conventions used throughout:
--   - UUID primary keys generated by gen_random_uuid().
--   - Timestamps are TIMESTAMPTZ with NOW() defaults.
--   - Foreign keys to auth.users use ON DELETE SET NULL or CASCADE
--     depending on whether the dependent row is meaningful without an
--     owning user.
--   - Email and slug fields are validated by CHECK constraints where it
--     matters.

-- ============================================================
-- ENUMS
-- ============================================================

DO $$ BEGIN
  CREATE TYPE price_type AS ENUM ('free', 'freemium', 'paid', 'unknown');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE platform_type AS ENUM ('web', 'local', 'api', 'hybrid', 'unknown');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE submission_status AS ENUM ('pending', 'approved', 'rejected');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================
-- TABLES (declared in dependency order)
-- ============================================================

CREATE TABLE IF NOT EXISTS categories (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL UNIQUE,
  slug        TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS submissions (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submitted_name           TEXT NOT NULL,
  submitted_url            TEXT,
  submitted_github_url     TEXT,
  submitted_description    TEXT,
  submitted_category_slug  TEXT,
  submitted_tags           TEXT[] DEFAULT '{}',
  submitter_email          TEXT NOT NULL,
  submitter_user_id        UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  submitter_ip             TEXT,
  status                   submission_status DEFAULT 'pending',
  admin_notes              TEXT,
  created_at               TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at              TIMESTAMPTZ,
  CONSTRAINT submissions_email_format
    CHECK (submitter_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  CONSTRAINT submissions_name_length
    CHECK (char_length(submitted_name) BETWEEN 1 AND 200),
  CONSTRAINT submissions_description_length
    CHECK (submitted_description IS NULL OR char_length(submitted_description) <= 5000)
);

CREATE TABLE IF NOT EXISTS tools (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                  TEXT NOT NULL,
  slug                  TEXT NOT NULL UNIQUE,
  short_description     TEXT NOT NULL,
  description           TEXT,
  website_url           TEXT,
  github_url            TEXT,
  docs_url              TEXT,
  category_id           UUID REFERENCES categories(id) ON DELETE SET NULL,
  license               TEXT,
  price                 price_type DEFAULT 'unknown',
  platform              platform_type DEFAULT 'unknown',
  difficulty            INTEGER CHECK (difficulty BETWEEN 1 AND 5) DEFAULT 3,
  gpu_required          BOOLEAN DEFAULT FALSE,
  min_vram_gb           INTEGER,
  is_open_source        BOOLEAN DEFAULT FALSE,
  is_self_hosted        BOOLEAN DEFAULT FALSE,
  is_offline_capable    BOOLEAN DEFAULT FALSE,
  tags                  TEXT[] DEFAULT '{}',
  featured              BOOLEAN DEFAULT FALSE,
  rating_avg            DECIMAL(3,2) DEFAULT 0,
  rating_count          INTEGER DEFAULT 0,
  status                TEXT DEFAULT 'published',
  source_submission_id  UUID REFERENCES submissions(id),
  claimed_by_user_id    UUID REFERENCES auth.users(id),
  claimed_at            TIMESTAMPTZ,
  last_major_update     TIMESTAMPTZ,
  major_update_notes    TEXT,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reviews (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tool_id     UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT,
  user_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ip_address  TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
  user_id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role              TEXT DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  display_name      TEXT,
  theme_preference  TEXT DEFAULT 'dark' CHECK (theme_preference IN ('light', 'dark')),
  last_known_ip     TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_favorites (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tool_id     UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, tool_id)
);

CREATE TABLE IF NOT EXISTS user_hidden_tools (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tool_id     UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, tool_id)
);

CREATE TABLE IF NOT EXISTS blog_posts (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug                TEXT NOT NULL UNIQUE,
  title               TEXT NOT NULL,
  excerpt             TEXT NOT NULL,
  content             TEXT NOT NULL,
  author_name         TEXT NOT NULL,
  author_slug         TEXT NOT NULL,
  cover_image_url     TEXT,
  published_at        TIMESTAMPTZ NOT NULL,
  meta_title          TEXT,
  meta_description    TEXT,
  tags                TEXT[] DEFAULT '{}',
  related_tool_slugs  TEXT[] DEFAULT '{}',
  is_published        BOOLEAN DEFAULT TRUE,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS site_settings (
  key         TEXT PRIMARY KEY,
  value       JSONB,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activity_log (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name  TEXT NOT NULL,
  operation   TEXT NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
  record_id   UUID,
  old_data    JSONB,
  new_data    JSONB,
  user_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ip_address  TEXT,
  user_agent  TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notification_preferences (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  email                   TEXT NOT NULL UNIQUE,
  notify_new_tools        BOOLEAN DEFAULT TRUE,
  notify_new_submissions  BOOLEAN DEFAULT TRUE,
  notify_new_reviews      BOOLEAN DEFAULT TRUE,
  notify_tool_updates     BOOLEAN DEFAULT TRUE,
  is_admin_notification   BOOLEAN DEFAULT FALSE,
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pending_ratings (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email       TEXT NOT NULL,
  tool_id     UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours')
);

CREATE TABLE IF NOT EXISTS bans (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ban_type     TEXT NOT NULL CHECK (ban_type IN ('user', 'ip', 'email')),
  user_id      UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  ip_address   TEXT,
  email        TEXT,
  reason       TEXT,
  banned_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  banned_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at   TIMESTAMPTZ,
  revoked_by   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  CONSTRAINT bans_target_matches_type CHECK (
    (ban_type = 'user'  AND user_id    IS NOT NULL AND ip_address IS NULL  AND email      IS NULL) OR
    (ban_type = 'ip'    AND ip_address IS NOT NULL AND user_id    IS NULL  AND email      IS NULL) OR
    (ban_type = 'email' AND email      IS NOT NULL AND user_id    IS NULL  AND ip_address IS NULL)
  ),
  CONSTRAINT bans_email_lowercase
    CHECK (email IS NULL OR email = lower(email))
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_categories_slug             ON categories (slug);

CREATE INDEX IF NOT EXISTS idx_tools_category              ON tools (category_id);
CREATE INDEX IF NOT EXISTS idx_tools_slug                  ON tools (slug);
CREATE INDEX IF NOT EXISTS idx_tools_featured              ON tools (featured) WHERE featured = TRUE;
CREATE INDEX IF NOT EXISTS idx_tools_open_source           ON tools (is_open_source) WHERE is_open_source = TRUE;
CREATE INDEX IF NOT EXISTS idx_tools_rating                ON tools (rating_avg DESC);
CREATE INDEX IF NOT EXISTS idx_tools_tags                  ON tools USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_tools_source_submission     ON tools (source_submission_id);
CREATE INDEX IF NOT EXISTS idx_tools_claimed_by            ON tools (claimed_by_user_id);

CREATE INDEX IF NOT EXISTS idx_submissions_status          ON submissions (status);

CREATE INDEX IF NOT EXISTS idx_reviews_tool                ON reviews (tool_id);
CREATE INDEX IF NOT EXISTS idx_reviews_tool_ip             ON reviews (tool_id, ip_address);

CREATE INDEX IF NOT EXISTS idx_user_favorites_user         ON user_favorites (user_id);
CREATE INDEX IF NOT EXISTS idx_user_favorites_tool         ON user_favorites (tool_id);

CREATE INDEX IF NOT EXISTS idx_user_hidden_user            ON user_hidden_tools (user_id);
CREATE INDEX IF NOT EXISTS idx_user_hidden_tool            ON user_hidden_tools (tool_id);

CREATE INDEX IF NOT EXISTS idx_blog_posts_slug             ON blog_posts (slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at     ON blog_posts (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_author_slug      ON blog_posts (author_slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_is_published     ON blog_posts (is_published);

CREATE INDEX IF NOT EXISTS idx_activity_log_table          ON activity_log (table_name);
CREATE INDEX IF NOT EXISTS idx_activity_log_operation      ON activity_log (operation);
CREATE INDEX IF NOT EXISTS idx_activity_log_created        ON activity_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_log_record         ON activity_log (record_id);

CREATE INDEX IF NOT EXISTS idx_notification_prefs_user     ON notification_preferences (user_id);
CREATE INDEX IF NOT EXISTS idx_notification_prefs_admin    ON notification_preferences (is_admin_notification) WHERE is_admin_notification = TRUE;

CREATE INDEX IF NOT EXISTS idx_pending_ratings_email       ON pending_ratings (email);
CREATE INDEX IF NOT EXISTS idx_pending_ratings_expires     ON pending_ratings (expires_at);

CREATE INDEX IF NOT EXISTS idx_bans_type                   ON bans (ban_type);
CREATE INDEX IF NOT EXISTS idx_bans_user                   ON bans (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bans_email                  ON bans (email)   WHERE email   IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bans_ip                     ON bans (ip_address) WHERE ip_address IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bans_active                 ON bans (banned_at DESC) WHERE revoked_at IS NULL;
