// NOTE: contains stale category slugs (agents-automation, llms-inference, rag-search, dev-tools, observability) merged in May 2026. Pending cleanup.

/**
 * Seed Script for BuilderAI.tools
 *
 * Run with: npm run seed
 *
 * Prerequisites:
 * 1. Create a Supabase project
 * 2. Run the schema.sql in Supabase SQL Editor
 * 3. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local
 */

import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

import { createClient } from '@supabase/supabase-js'

// API key loaded from environment variable. Never hardcode secrets.
const supabaseUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing environment variables. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseServiceKey)

// Categories
const categories = [
  { 
    name: 'LLMs & Inference', 
    slug: 'llms-inference', 
    description: 'Large language models and inference engines for running AI models locally or in the cloud' 
  },
  { 
    name: 'Agents & Automation', 
    slug: 'agents-automation', 
    description: 'AI agents, orchestration frameworks, and automation tools for complex workflows' 
  },
  { 
    name: 'RAG & Search', 
    slug: 'rag-search', 
    description: 'Retrieval-augmented generation, vector databases, and semantic search tools' 
  },
  { 
    name: 'Image Generation', 
    slug: 'image-generation', 
    description: 'AI image generation, editing, and manipulation tools' 
  },
  { 
    name: 'Video Generation', 
    slug: 'video-generation', 
    description: 'AI video generation, editing, and processing tools' 
  },
  { 
    name: 'Audio & Speech', 
    slug: 'audio-speech', 
    description: 'Speech-to-text, text-to-speech, audio processing, and voice cloning tools' 
  },
  { 
    name: 'Dev Tools', 
    slug: 'dev-tools', 
    description: 'Developer tools, libraries, and frameworks for building AI applications' 
  },
  { 
    name: 'UI & Chat Interfaces', 
    slug: 'ui-chat-interfaces', 
    description: 'User interfaces, chat UIs, and frontend tools for AI applications' 
  },
  { 
    name: 'Datasets & Training', 
    slug: 'datasets-training', 
    description: 'Dataset management, model training, and fine-tuning tools' 
  },
  { 
    name: 'Observability', 
    slug: 'observability', 
    description: 'Monitoring, logging, tracing, and analytics for AI applications' 
  },
]

// Tools - organized by category
const tools = [
  // LLMs & Inference
  {
    name: 'Ollama',
    slug: 'ollama',
    short_description: 'Run large language models locally with a simple CLI interface',
    description: 'Ollama makes it easy to run large language models locally. It bundles model weights, configurations, and datasets into a single package called a Modelfile. Supports Llama 2, Mistral, Gemma, and many other models with a simple command-line interface.',
    website_url: 'https://ollama.ai',
    github_url: 'https://github.com/ollama/ollama',
    docs_url: 'https://github.com/ollama/ollama/blob/main/README.md',
    category_slug: 'llms-inference',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 1,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['llm', 'inference', 'local', 'cli'],
    featured: true,
  },
  {
    name: 'llama.cpp',
    slug: 'llama-cpp',
    short_description: 'Port of Meta\'s LLaMA model in C/C++ for efficient CPU inference',
    description: 'llama.cpp is a port of Facebook\'s LLaMA model in C/C++. It enables inference of LLaMA models with minimal dependencies, supporting quantization for CPU-only inference with reasonable performance.',
    website_url: null,
    github_url: 'https://github.com/ggerganov/llama.cpp',
    docs_url: 'https://github.com/ggerganov/llama.cpp/blob/master/README.md',
    category_slug: 'llms-inference',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['llm', 'inference', 'c++', 'cpu', 'quantization'],
    featured: true,
  },
  {
    name: 'vLLM',
    slug: 'vllm',
    short_description: 'High-throughput LLM serving engine with PagedAttention',
    description: 'vLLM is a fast and easy-to-use library for LLM inference and serving. It achieves high throughput with PagedAttention, an attention algorithm that efficiently manages attention key and value memory.',
    website_url: 'https://vllm.ai',
    github_url: 'https://github.com/vllm-project/vllm',
    docs_url: 'https://docs.vllm.ai',
    category_slug: 'llms-inference',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: true,
    min_vram_gb: 16,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['llm', 'inference', 'serving', 'high-throughput'],
    featured: true,
  },
  {
    name: 'Text Generation Inference',
    slug: 'text-generation-inference',
    short_description: 'Hugging Face\'s high-performance text generation server',
    description: 'Text Generation Inference (TGI) is a toolkit for deploying and serving Large Language Models. It includes optimized implementations for popular models and supports tensor parallelism for multi-GPU inference.',
    website_url: 'https://huggingface.co/docs/text-generation-inference',
    github_url: 'https://github.com/huggingface/text-generation-inference',
    docs_url: 'https://huggingface.co/docs/text-generation-inference',
    category_slug: 'llms-inference',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 4,
    gpu_required: true,
    min_vram_gb: 16,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['llm', 'inference', 'huggingface', 'serving'],
    featured: false,
  },
  {
    name: 'LiteLLM',
    slug: 'litellm',
    short_description: 'Unified API to call 100+ LLM providers with OpenAI format',
    description: 'LiteLLM provides a unified interface to call 100+ LLM APIs using the OpenAI format. It supports load balancing, fallbacks, spend tracking, and model routing across providers like OpenAI, Anthropic, Azure, and more.',
    website_url: 'https://litellm.ai',
    github_url: 'https://github.com/BerriAI/litellm',
    docs_url: 'https://docs.litellm.ai',
    category_slug: 'llms-inference',
    license: 'MIT',
    price: 'free',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['llm', 'api', 'proxy', 'unified'],
    featured: true,
  },

  // Agents & Automation
  {
    name: 'LangChain',
    slug: 'langchain',
    short_description: 'Framework for building applications with large language models',
    description: 'LangChain is a framework for developing applications powered by language models. It enables applications that are context-aware and reason, connecting language models to sources of context and relying on them for reasoning.',
    website_url: 'https://langchain.com',
    github_url: 'https://github.com/langchain-ai/langchain',
    docs_url: 'https://python.langchain.com/docs',
    category_slug: 'agents-automation',
    license: 'MIT',
    price: 'free',
    platform: 'hybrid',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['framework', 'agents', 'chains', 'python'],
    featured: true,
  },
  {
    name: 'LlamaIndex',
    slug: 'llamaindex',
    short_description: 'Data framework for LLM applications with data ingestion and indexing',
    description: 'LlamaIndex (formerly GPT Index) is a data framework for LLM applications. It provides tools for data ingestion, data indexing, and building query engines to retrieve and augment LLM responses with your data.',
    website_url: 'https://llamaindex.ai',
    github_url: 'https://github.com/run-llama/llama_index',
    docs_url: 'https://docs.llamaindex.ai',
    category_slug: 'agents-automation',
    license: 'MIT',
    price: 'free',
    platform: 'hybrid',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['rag', 'indexing', 'data', 'python'],
    featured: true,
  },
  {
    name: 'AutoGen',
    slug: 'autogen',
    short_description: 'Microsoft\'s framework for building multi-agent AI systems',
    description: 'AutoGen is a framework from Microsoft for building multi-agent AI systems. It enables the creation of workflows with multiple agents that can converse with each other to complete complex tasks.',
    website_url: 'https://microsoft.github.io/autogen',
    github_url: 'https://github.com/microsoft/autogen',
    docs_url: 'https://microsoft.github.io/autogen/docs',
    category_slug: 'agents-automation',
    license: 'MIT',
    price: 'free',
    platform: 'hybrid',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['agents', 'multi-agent', 'microsoft', 'python'],
    featured: true,
  },
  {
    name: 'CrewAI',
    slug: 'crewai',
    short_description: 'Framework for orchestrating role-playing autonomous AI agents',
    description: 'CrewAI is a cutting-edge framework for orchestrating role-playing, autonomous AI agents. By fostering collaborative intelligence, CrewAI empowers agents to work together seamlessly, tackling complex tasks.',
    website_url: 'https://crewai.com',
    github_url: 'https://github.com/joaomdmoura/crewai',
    docs_url: 'https://docs.crewai.com',
    category_slug: 'agents-automation',
    license: 'MIT',
    price: 'free',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['agents', 'crew', 'autonomous', 'python'],
    featured: false,
  },
  {
    name: 'Haystack',
    slug: 'haystack',
    short_description: 'End-to-end NLP framework for building search and QA systems',
    description: 'Haystack is an end-to-end NLP framework that enables you to build production-ready applications using LLMs and transformer models. Build semantic search, question answering, and conversational AI systems.',
    website_url: 'https://haystack.deepset.ai',
    github_url: 'https://github.com/deepset-ai/haystack',
    docs_url: 'https://docs.haystack.deepset.ai',
    category_slug: 'agents-automation',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'hybrid',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['nlp', 'search', 'qa', 'pipeline'],
    featured: false,
  },

  // RAG & Search
  {
    name: 'Qdrant',
    slug: 'qdrant',
    short_description: 'High-performance vector database for similarity search',
    description: 'Qdrant is a vector similarity search engine and vector database. It provides a production-ready service with a convenient API to store, search, and manage vectors with an extended filtering support.',
    website_url: 'https://qdrant.tech',
    github_url: 'https://github.com/qdrant/qdrant',
    docs_url: 'https://qdrant.tech/documentation',
    category_slug: 'rag-search',
    license: 'Apache-2.0',
    price: 'freemium',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['vector-database', 'search', 'rust', 'similarity'],
    featured: true,
  },
  {
    name: 'Chroma',
    slug: 'chroma',
    short_description: 'Open-source embedding database for AI applications',
    description: 'Chroma is the AI-native open-source embedding database. It makes it easy to build LLM apps by making knowledge, facts, and skills pluggable for LLMs. Simple to use with just 4 functions.',
    website_url: 'https://trychroma.com',
    github_url: 'https://github.com/chroma-core/chroma',
    docs_url: 'https://docs.trychroma.com',
    category_slug: 'rag-search',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'hybrid',
    difficulty: 1,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['vector-database', 'embeddings', 'python', 'simple'],
    featured: true,
  },
  {
    name: 'Weaviate',
    slug: 'weaviate',
    short_description: 'AI-native vector database with built-in ML modules',
    description: 'Weaviate is an open-source vector database that stores both objects and vectors. It allows for combining vector search with structured filtering with the fault-tolerance of a cloud-native database.',
    website_url: 'https://weaviate.io',
    github_url: 'https://github.com/weaviate/weaviate',
    docs_url: 'https://weaviate.io/developers/weaviate',
    category_slug: 'rag-search',
    license: 'BSD-3-Clause',
    price: 'freemium',
    platform: 'hybrid',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['vector-database', 'search', 'graphql', 'ml-modules'],
    featured: false,
  },
  {
    name: 'Milvus',
    slug: 'milvus',
    short_description: 'Cloud-native vector database for scalable similarity search',
    description: 'Milvus is an open-source vector database built for scalable similarity search. It supports adding, deleting, updating, and near real-time search of vectors on a trillion-byte scale.',
    website_url: 'https://milvus.io',
    github_url: 'https://github.com/milvus-io/milvus',
    docs_url: 'https://milvus.io/docs',
    category_slug: 'rag-search',
    license: 'Apache-2.0',
    price: 'freemium',
    platform: 'hybrid',
    difficulty: 4,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['vector-database', 'distributed', 'scalable', 'kubernetes'],
    featured: false,
  },
  {
    name: 'Pinecone',
    slug: 'pinecone',
    short_description: 'Managed vector database for machine learning applications',
    description: 'Pinecone is a fully managed vector database that makes it easy to add vector search to production applications. It provides blazing fast vector similarity search without infrastructure hassle.',
    website_url: 'https://pinecone.io',
    github_url: null,
    docs_url: 'https://docs.pinecone.io',
    category_slug: 'rag-search',
    license: null,
    price: 'freemium',
    platform: 'web',
    difficulty: 1,
    gpu_required: false,
    is_open_source: false,
    is_self_hosted: false,
    is_offline_capable: false,
    tags: ['vector-database', 'managed', 'cloud', 'enterprise'],
    featured: false,
  },

  // Image Generation
  {
    name: 'Stable Diffusion WebUI',
    slug: 'stable-diffusion-webui',
    short_description: 'Feature-rich web interface for Stable Diffusion image generation',
    description: 'AUTOMATIC1111\'s Stable Diffusion Web UI is a browser interface based on Gradio. It provides a rich set of features including txt2img, img2img, outpainting, inpainting, and many advanced settings for image generation.',
    website_url: null,
    github_url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    docs_url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki',
    category_slug: 'image-generation',
    license: 'AGPL-3.0',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: true,
    min_vram_gb: 4,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['stable-diffusion', 'image-generation', 'webui', 'gradio'],
    featured: true,
  },
  {
    name: 'ComfyUI',
    slug: 'comfyui',
    short_description: 'Node-based UI for powerful Stable Diffusion workflows',
    description: 'ComfyUI is a powerful and modular Stable Diffusion GUI with a node-based interface. It lets you design and execute advanced stable diffusion pipelines using a flowchart-like approach.',
    website_url: null,
    github_url: 'https://github.com/comfyanonymous/ComfyUI',
    docs_url: 'https://github.com/comfyanonymous/ComfyUI/blob/master/README.md',
    category_slug: 'image-generation',
    license: 'GPL-3.0',
    price: 'free',
    platform: 'local',
    difficulty: 4,
    gpu_required: true,
    min_vram_gb: 4,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['stable-diffusion', 'image-generation', 'nodes', 'workflows'],
    featured: true,
  },
  {
    name: 'Fooocus',
    slug: 'fooocus',
    short_description: 'Simplified Stable Diffusion interface inspired by Midjourney',
    description: 'Fooocus is an image generating software based on Gradio. It rethinks SD\'s designs to be more human-centered, making the interface simple like Midjourney while maintaining the power of SD.',
    website_url: null,
    github_url: 'https://github.com/lllyasviel/Fooocus',
    docs_url: 'https://github.com/lllyasviel/Fooocus/blob/main/readme.md',
    category_slug: 'image-generation',
    license: 'GPL-3.0',
    price: 'free',
    platform: 'local',
    difficulty: 2,
    gpu_required: true,
    min_vram_gb: 4,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['stable-diffusion', 'image-generation', 'simple', 'midjourney-like'],
    featured: false,
  },
  {
    name: 'Invoke AI',
    slug: 'invokeai',
    short_description: 'Creative AI toolkit for Stable Diffusion with unified canvas',
    description: 'InvokeAI is a leading creative engine for Stable Diffusion models. It provides an industry-leading WebUI, supporting both Stable Diffusion 1.x and 2.x models, and features a unified canvas.',
    website_url: 'https://invoke.ai',
    github_url: 'https://github.com/invoke-ai/InvokeAI',
    docs_url: 'https://invoke-ai.github.io/InvokeAI',
    category_slug: 'image-generation',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: true,
    min_vram_gb: 4,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['stable-diffusion', 'image-generation', 'canvas', 'creative'],
    featured: false,
  },
  {
    name: 'Diffusers',
    slug: 'diffusers',
    short_description: 'Hugging Face library for state-of-the-art diffusion models',
    description: 'Diffusers is a Hugging Face library for state-of-the-art pretrained diffusion models for generating images, audio, and 3D structures. It provides a modular toolbox for training and inference.',
    website_url: 'https://huggingface.co/docs/diffusers',
    github_url: 'https://github.com/huggingface/diffusers',
    docs_url: 'https://huggingface.co/docs/diffusers',
    category_slug: 'image-generation',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: true,
    min_vram_gb: 8,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['diffusion', 'huggingface', 'python', 'library'],
    featured: false,
  },

  // Video Generation
  {
    name: 'Stable Video Diffusion',
    slug: 'stable-video-diffusion',
    short_description: 'AI video generation model from Stability AI',
    description: 'Stable Video Diffusion is a generative AI video model released by Stability AI. It creates short video clips from text or image prompts using diffusion-based generation techniques.',
    website_url: 'https://stability.ai/stable-video',
    github_url: 'https://github.com/Stability-AI/generative-models',
    docs_url: 'https://github.com/Stability-AI/generative-models/blob/main/README.md',
    category_slug: 'video-generation',
    license: 'Stability AI License',
    price: 'free',
    platform: 'local',
    difficulty: 4,
    gpu_required: true,
    min_vram_gb: 16,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['video', 'diffusion', 'stability-ai', 'generation'],
    featured: true,
  },
  {
    name: 'AnimateDiff',
    slug: 'animatediff',
    short_description: 'Turn text-to-image models into animation generators',
    description: 'AnimateDiff is a plugin that enables most text-to-image models to generate animations. It provides a practical framework for animating personalized text-to-image models without specific tuning.',
    website_url: null,
    github_url: 'https://github.com/guoyww/AnimateDiff',
    docs_url: 'https://animatediff.github.io',
    category_slug: 'video-generation',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 4,
    gpu_required: true,
    min_vram_gb: 12,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['video', 'animation', 'stable-diffusion', 'motion'],
    featured: false,
  },
  {
    name: 'Deforum',
    slug: 'deforum',
    short_description: 'AI animation tool for creating dynamic video content',
    description: 'Deforum is an open-source project for creating AI-generated animations using Stable Diffusion. It provides tools for keyframe animation, camera movements, and audio-reactive visuals.',
    website_url: 'https://deforum.art',
    github_url: 'https://github.com/deforum-art/deforum-stable-diffusion',
    docs_url: 'https://github.com/deforum-art/deforum-stable-diffusion/blob/main/README.md',
    category_slug: 'video-generation',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 4,
    gpu_required: true,
    min_vram_gb: 8,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['video', 'animation', 'deforum', 'keyframes'],
    featured: false,
  },

  // Audio & Speech
  {
    name: 'Whisper',
    slug: 'whisper',
    short_description: 'OpenAI\'s powerful speech recognition model',
    description: 'Whisper is a general-purpose speech recognition model from OpenAI. It is trained on a large dataset of diverse audio and is also a multitasking model that can perform multilingual speech recognition and translation.',
    website_url: 'https://openai.com/research/whisper',
    github_url: 'https://github.com/openai/whisper',
    docs_url: 'https://github.com/openai/whisper/blob/main/README.md',
    category_slug: 'audio-speech',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['speech-to-text', 'transcription', 'openai', 'multilingual'],
    featured: true,
  },
  {
    name: 'faster-whisper',
    slug: 'faster-whisper',
    short_description: 'CTranslate2-based Whisper with 4x faster transcription',
    description: 'faster-whisper is a reimplementation of OpenAI\'s Whisper model using CTranslate2. It achieves up to 4x faster transcription while using less memory than the original implementation.',
    website_url: null,
    github_url: 'https://github.com/SYSTRAN/faster-whisper',
    docs_url: 'https://github.com/SYSTRAN/faster-whisper/blob/master/README.md',
    category_slug: 'audio-speech',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['speech-to-text', 'whisper', 'fast', 'ctranslate2'],
    featured: true,
  },
  {
    name: 'Piper TTS',
    slug: 'piper-tts',
    short_description: 'Fast, local neural text-to-speech for home automation',
    description: 'Piper is a fast, local neural text-to-speech system. It is optimized for Raspberry Pi 4 and supports multiple languages with various voice options. Perfect for home automation and accessibility.',
    website_url: 'https://rhasspy.github.io/piper-samples',
    github_url: 'https://github.com/rhasspy/piper',
    docs_url: 'https://github.com/rhasspy/piper/blob/master/README.md',
    category_slug: 'audio-speech',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['text-to-speech', 'tts', 'neural', 'raspberry-pi'],
    featured: true,
  },
  {
    name: 'Coqui TTS',
    slug: 'coqui-tts',
    short_description: 'Deep learning toolkit for text-to-speech synthesis',
    description: 'Coqui TTS is a deep learning toolkit for Text-to-Speech. It provides pretrained models, tools for training custom voices, and implements the latest TTS architectures.',
    website_url: 'https://coqui.ai',
    github_url: 'https://github.com/coqui-ai/TTS',
    docs_url: 'https://tts.readthedocs.io',
    category_slug: 'audio-speech',
    license: 'MPL-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['text-to-speech', 'tts', 'deep-learning', 'voice-cloning'],
    featured: false,
  },
  {
    name: 'Bark',
    slug: 'bark',
    short_description: 'Transformer-based text-to-audio model from Suno',
    description: 'Bark is a transformer-based text-to-audio model created by Suno. It can generate highly realistic, multilingual speech as well as other audio like music, background noise, and sound effects.',
    website_url: 'https://suno.ai',
    github_url: 'https://github.com/suno-ai/bark',
    docs_url: 'https://github.com/suno-ai/bark/blob/main/README.md',
    category_slug: 'audio-speech',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 2,
    gpu_required: true,
    min_vram_gb: 8,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['text-to-speech', 'audio', 'music', 'sound-effects'],
    featured: false,
  },
  {
    name: 'WhisperX',
    slug: 'whisperx',
    short_description: 'Whisper with word-level timestamps and speaker diarization',
    description: 'WhisperX provides fast automatic speech recognition with word-level timestamps and speaker diarization. It combines Whisper with forced alignment and VAD for improved accuracy.',
    website_url: null,
    github_url: 'https://github.com/m-bain/whisperX',
    docs_url: 'https://github.com/m-bain/whisperX/blob/main/README.md',
    category_slug: 'audio-speech',
    license: 'BSD-4-Clause',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['speech-to-text', 'whisper', 'timestamps', 'diarization'],
    featured: false,
  },

  // Dev Tools
  {
    name: 'Transformers',
    slug: 'transformers',
    short_description: 'Hugging Face library for state-of-the-art NLP models',
    description: 'Transformers provides thousands of pretrained models for NLP, computer vision, audio, and multimodal tasks. It offers a simple API for downloading and training models with PyTorch, TensorFlow, and JAX.',
    website_url: 'https://huggingface.co/transformers',
    github_url: 'https://github.com/huggingface/transformers',
    docs_url: 'https://huggingface.co/docs/transformers',
    category_slug: 'dev-tools',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['nlp', 'models', 'huggingface', 'pytorch'],
    featured: true,
  },
  {
    name: 'LangServe',
    slug: 'langserve',
    short_description: 'Deploy LangChain runnables as REST APIs',
    description: 'LangServe helps developers deploy LangChain runnables and chains as REST APIs. It automatically generates input/output schemas, includes a playground, and handles async operations.',
    website_url: 'https://langchain.com',
    github_url: 'https://github.com/langchain-ai/langserve',
    docs_url: 'https://python.langchain.com/docs/langserve',
    category_slug: 'dev-tools',
    license: 'MIT',
    price: 'free',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['langchain', 'api', 'deployment', 'rest'],
    featured: false,
  },
  {
    name: 'Vercel AI SDK',
    slug: 'vercel-ai-sdk',
    short_description: 'TypeScript toolkit for building AI-powered web applications',
    description: 'The Vercel AI SDK is a TypeScript toolkit designed to help developers build AI-powered applications with React, Next.js, Vue, Svelte, and Node.js. It provides streaming UI components and hooks.',
    website_url: 'https://sdk.vercel.ai',
    github_url: 'https://github.com/vercel/ai',
    docs_url: 'https://sdk.vercel.ai/docs',
    category_slug: 'dev-tools',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['typescript', 'react', 'nextjs', 'streaming'],
    featured: true,
  },
  {
    name: 'Instructor',
    slug: 'instructor',
    short_description: 'Structured output extraction from LLMs with Pydantic',
    description: 'Instructor makes it easy to get structured data from LLMs. It uses Pydantic for validation, works with multiple LLM providers, and handles retries, streaming, and partial responses.',
    website_url: 'https://python.useinstructor.com',
    github_url: 'https://github.com/jxnl/instructor',
    docs_url: 'https://python.useinstructor.com',
    category_slug: 'dev-tools',
    license: 'MIT',
    price: 'free',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['structured-output', 'pydantic', 'llm', 'extraction'],
    featured: false,
  },
  {
    name: 'GGML',
    slug: 'ggml',
    short_description: 'Tensor library for machine learning on commodity hardware',
    description: 'GGML is a tensor library for machine learning. It is designed to enable large models and high performance on commodity hardware, and is the foundation for llama.cpp and whisper.cpp.',
    website_url: null,
    github_url: 'https://github.com/ggerganov/ggml',
    docs_url: 'https://github.com/ggerganov/ggml/blob/master/README.md',
    category_slug: 'dev-tools',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 5,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['tensor', 'c', 'low-level', 'quantization'],
    featured: false,
  },

  // UI & Chat Interfaces
  {
    name: 'Open WebUI',
    slug: 'open-webui',
    short_description: 'Self-hosted ChatGPT-like interface for local LLMs',
    description: 'Open WebUI (formerly Ollama WebUI) is a feature-rich, self-hosted web interface for LLMs. It supports Ollama and OpenAI-compatible APIs, with features like chat history, RAG, and multi-user support.',
    website_url: 'https://openwebui.com',
    github_url: 'https://github.com/open-webui/open-webui',
    docs_url: 'https://docs.openwebui.com',
    category_slug: 'ui-chat-interfaces',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['webui', 'chat', 'ollama', 'self-hosted'],
    featured: true,
  },
  {
    name: 'Gradio',
    slug: 'gradio',
    short_description: 'Build ML demos and web apps with Python in minutes',
    description: 'Gradio is an open-source Python library for building machine learning and data science demos and web apps. Create interfaces for any ML model with just a few lines of code.',
    website_url: 'https://gradio.app',
    github_url: 'https://github.com/gradio-app/gradio',
    docs_url: 'https://gradio.app/docs',
    category_slug: 'ui-chat-interfaces',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'hybrid',
    difficulty: 1,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['demo', 'webui', 'python', 'ml'],
    featured: true,
  },
  {
    name: 'Streamlit',
    slug: 'streamlit',
    short_description: 'Turn Python scripts into shareable web apps',
    description: 'Streamlit turns data scripts into shareable web apps in minutes. All in pure Python, no front-end experience required. Perfect for ML demos, data exploration, and prototyping.',
    website_url: 'https://streamlit.io',
    github_url: 'https://github.com/streamlit/streamlit',
    docs_url: 'https://docs.streamlit.io',
    category_slug: 'ui-chat-interfaces',
    license: 'Apache-2.0',
    price: 'freemium',
    platform: 'hybrid',
    difficulty: 1,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['python', 'webui', 'data', 'dashboards'],
    featured: true,
  },
  {
    name: 'Chainlit',
    slug: 'chainlit',
    short_description: 'Build production-ready conversational AI apps in minutes',
    description: 'Chainlit is an open-source Python package that makes it easy to build production-ready Conversational AI. It integrates with LangChain, LlamaIndex, and other frameworks.',
    website_url: 'https://chainlit.io',
    github_url: 'https://github.com/Chainlit/chainlit',
    docs_url: 'https://docs.chainlit.io',
    category_slug: 'ui-chat-interfaces',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['chat', 'conversational-ai', 'python', 'langchain'],
    featured: false,
  },
  {
    name: 'Text Generation WebUI',
    slug: 'text-generation-webui',
    short_description: 'Gradio web UI for running large language models',
    description: 'oobabooga\'s text-generation-webui is a Gradio web UI for large language models. It supports many models and features like chat mode, notebook mode, and training LoRAs.',
    website_url: null,
    github_url: 'https://github.com/oobabooga/text-generation-webui',
    docs_url: 'https://github.com/oobabooga/text-generation-webui/wiki',
    category_slug: 'ui-chat-interfaces',
    license: 'AGPL-3.0',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: true,
    min_vram_gb: 8,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['webui', 'llm', 'gradio', 'oobabooga'],
    featured: false,
  },
  {
    name: 'LibreChat',
    slug: 'librechat',
    short_description: 'Enhanced ChatGPT clone with multi-provider support',
    description: 'LibreChat is an enhanced ChatGPT clone that supports multiple AI providers including OpenAI, Azure, Anthropic, and Google. Features include plugins, presets, and conversation sharing.',
    website_url: 'https://librechat.ai',
    github_url: 'https://github.com/danny-avila/LibreChat',
    docs_url: 'https://docs.librechat.ai',
    category_slug: 'ui-chat-interfaces',
    license: 'MIT',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['chat', 'chatgpt', 'multi-provider', 'plugins'],
    featured: false,
  },

  // Datasets & Training
  {
    name: 'Hugging Face Datasets',
    slug: 'huggingface-datasets',
    short_description: 'Library for accessing and sharing ML datasets',
    description: 'Hugging Face Datasets is a library for easily accessing and sharing datasets for NLP, computer vision, and audio tasks. It provides efficient data loading with Apache Arrow backend.',
    website_url: 'https://huggingface.co/docs/datasets',
    github_url: 'https://github.com/huggingface/datasets',
    docs_url: 'https://huggingface.co/docs/datasets',
    category_slug: 'datasets-training',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['datasets', 'huggingface', 'data', 'ml'],
    featured: true,
  },
  {
    name: 'Axolotl',
    slug: 'axolotl',
    short_description: 'Tool for fine-tuning LLMs with various configurations',
    description: 'Axolotl is a tool designed to streamline the fine-tuning of various AI models. It supports multiple architectures and training techniques including LoRA, QLoRA, and full fine-tuning.',
    website_url: null,
    github_url: 'https://github.com/OpenAccess-AI-Collective/axolotl',
    docs_url: 'https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/README.md',
    category_slug: 'datasets-training',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 4,
    gpu_required: true,
    min_vram_gb: 16,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['fine-tuning', 'lora', 'training', 'llm'],
    featured: true,
  },
  {
    name: 'PEFT',
    slug: 'peft',
    short_description: 'Hugging Face library for parameter-efficient fine-tuning',
    description: 'PEFT (Parameter-Efficient Fine-Tuning) is a library for efficiently adapting large pretrained models to various downstream applications. It supports methods like LoRA, Prefix Tuning, and more.',
    website_url: 'https://huggingface.co/docs/peft',
    github_url: 'https://github.com/huggingface/peft',
    docs_url: 'https://huggingface.co/docs/peft',
    category_slug: 'datasets-training',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: true,
    min_vram_gb: 8,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['fine-tuning', 'lora', 'peft', 'huggingface'],
    featured: false,
  },
  {
    name: 'Unsloth',
    slug: 'unsloth',
    short_description: 'Fine-tune LLMs 2x faster with 80% less memory',
    description: 'Unsloth makes fine-tuning Llama, Mistral, and other models 2x faster while using 80% less memory. It supports QLoRA and LoRA with automatic patching of Hugging Face models.',
    website_url: 'https://unsloth.ai',
    github_url: 'https://github.com/unslothai/unsloth',
    docs_url: 'https://github.com/unslothai/unsloth/wiki',
    category_slug: 'datasets-training',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'local',
    difficulty: 3,
    gpu_required: true,
    min_vram_gb: 8,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['fine-tuning', 'fast', 'memory-efficient', 'lora'],
    featured: true,
  },
  {
    name: 'Label Studio',
    slug: 'label-studio',
    short_description: 'Open source data labeling platform for ML projects',
    description: 'Label Studio is an open source data labeling tool. It supports labeling for images, audio, text, time series, and multi-domain data types. Integrates with ML models for pre-labeling.',
    website_url: 'https://labelstud.io',
    github_url: 'https://github.com/HumanSignal/label-studio',
    docs_url: 'https://labelstud.io/guide',
    category_slug: 'datasets-training',
    license: 'Apache-2.0',
    price: 'freemium',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['labeling', 'annotation', 'datasets', 'ml'],
    featured: false,
  },

  // Observability
  {
    name: 'Langfuse',
    slug: 'langfuse',
    short_description: 'Open source LLM engineering platform for tracing and analytics',
    description: 'Langfuse is an open source LLM engineering platform. It provides tracing, prompt management, evaluations, and analytics for debugging and improving LLM applications.',
    website_url: 'https://langfuse.com',
    github_url: 'https://github.com/langfuse/langfuse',
    docs_url: 'https://langfuse.com/docs',
    category_slug: 'observability',
    license: 'MIT',
    price: 'freemium',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['tracing', 'observability', 'analytics', 'llm'],
    featured: true,
  },
  {
    name: 'LangSmith',
    slug: 'langsmith',
    short_description: 'LangChain\'s platform for debugging and monitoring LLM apps',
    description: 'LangSmith is a platform for building production-grade LLM applications. It provides debugging, testing, evaluation, and monitoring capabilities for LangChain applications.',
    website_url: 'https://smith.langchain.com',
    github_url: null,
    docs_url: 'https://docs.smith.langchain.com',
    category_slug: 'observability',
    license: null,
    price: 'freemium',
    platform: 'web',
    difficulty: 2,
    gpu_required: false,
    is_open_source: false,
    is_self_hosted: false,
    is_offline_capable: false,
    tags: ['langchain', 'debugging', 'monitoring', 'evaluation'],
    featured: false,
  },
  {
    name: 'Phoenix',
    slug: 'phoenix',
    short_description: 'AI observability and evaluation from Arize',
    description: 'Phoenix by Arize is an open-source AI observability tool. It provides tracing, evaluation, and analysis for LLM applications with support for embeddings visualization and prompt engineering.',
    website_url: 'https://phoenix.arize.com',
    github_url: 'https://github.com/Arize-ai/phoenix',
    docs_url: 'https://docs.arize.com/phoenix',
    category_slug: 'observability',
    license: 'Elastic-2.0',
    price: 'free',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: false,
    tags: ['observability', 'tracing', 'evaluation', 'embeddings'],
    featured: false,
  },
  {
    name: 'Weights & Biases',
    slug: 'wandb',
    short_description: 'ML experiment tracking, visualization, and collaboration',
    description: 'Weights & Biases (W&B) is an MLOps platform for experiment tracking, dataset versioning, and model management. It helps teams build better models faster with collaborative tools.',
    website_url: 'https://wandb.ai',
    github_url: 'https://github.com/wandb/wandb',
    docs_url: 'https://docs.wandb.ai',
    category_slug: 'observability',
    license: 'MIT',
    price: 'freemium',
    platform: 'hybrid',
    difficulty: 2,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: false,
    is_offline_capable: false,
    tags: ['mlops', 'experiment-tracking', 'visualization', 'collaboration'],
    featured: true,
  },
  {
    name: 'MLflow',
    slug: 'mlflow',
    short_description: 'Open source platform for the ML lifecycle',
    description: 'MLflow is an open source platform for managing the end-to-end machine learning lifecycle. It includes experiment tracking, model registry, project packaging, and deployment tools.',
    website_url: 'https://mlflow.org',
    github_url: 'https://github.com/mlflow/mlflow',
    docs_url: 'https://mlflow.org/docs/latest/index.html',
    category_slug: 'observability',
    license: 'Apache-2.0',
    price: 'free',
    platform: 'hybrid',
    difficulty: 3,
    gpu_required: false,
    is_open_source: true,
    is_self_hosted: true,
    is_offline_capable: true,
    tags: ['mlops', 'lifecycle', 'tracking', 'registry'],
    featured: false,
  },
]

async function seed() {
  console.log('Starting seed...\n')

  // Insert categories
  console.log('Inserting categories...')
  const { data: insertedCategories, error: catError } = await supabase
    .from('categories')
    .upsert(categories, { onConflict: 'slug' })
    .select()

  if (catError) {
    console.error('Error inserting categories:', catError)
    return
  }
  console.log(`Inserted ${insertedCategories?.length} categories\n`)

  // Create category lookup
  const categoryMap: Record<string, string> = {}
  insertedCategories?.forEach((cat) => {
    categoryMap[cat.slug] = cat.id
  })

  // Insert tools
  console.log('Inserting tools...')
  let successCount = 0
  let errorCount = 0

  for (const tool of tools) {
    const { category_slug, ...toolData } = tool
    const category_id = categoryMap[category_slug] || null

    const { error: toolError } = await supabase
      .from('tools')
      .upsert(
        { ...toolData, category_id },
        { onConflict: 'slug' }
      )

    if (toolError) {
      console.error(`Error inserting ${tool.name}:`, toolError.message)
      errorCount++
    } else {
      console.log(`✓ ${tool.name}`)
      successCount++
    }
  }

  console.log(`\nSeed complete!`)
  console.log(`Categories: ${insertedCategories?.length}`)
  console.log(`Tools: ${successCount} success, ${errorCount} errors`)
}

seed().catch(console.error)
